name: otter
description: A sample command-line application.
version: 0.8.0

environment:
  sdk: '>=2.18.5 <3.0.0'

dependencies:
  antlr4: 4.11.0
#   path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
